In [1]:
import numpy as np
import pandas as pd
import re
import os
from table import Table

In [73]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [2]:
tables = {}

directory = "tables/"
for filename in os.listdir(directory):
    if filename.endswith(".xls"):
        file_directory = os.path.join(directory, filename)
        table = Table(file_directory, "2019")
        tables[table.id] = table

In [3]:
tables

{'203.10': <table.Table at 0x1eaf22aa670>,
 '203.50': <table.Table at 0x1eaf22aa8e0>,
 '204.10': <table.Table at 0x1eaf43c12b0>,
 '204.27': <table.Table at 0x1eaf11eac10>,
 '213.10': <table.Table at 0x1eaf12dde80>,
 '215.10': <table.Table at 0x1eaf47bcf10>,
 '217.10': <table.Table at 0x1eaf4889520>,
 '217.15': <table.Table at 0x1eaf4af0fd0>,
 '219.70': <table.Table at 0x1eaf4af0460>,
 '236.30': <table.Table at 0x1eaf4c0ffd0>,
 '318.45': <table.Table at 0x1eaf4b5f7f0>}

In [4]:
tab = tables['203.10']

In [5]:
df = tab.raw_df.iloc[tab.header_lines+1:tab.end_row+1, :]
df

0          1        2        3        4        5        6        7   \
5       1980    40877.5  27646.5   96.133  2593.11  2894.47  2799.59  2893.01   
6       1985      39422  27034.2  151.335  3041.07  3238.86  2940.99  2894.52   
7       1990    41216.7  29875.9  303.319  3306.33  3499.43  3327.45  3296.72   
8       1991    42046.9  30502.5  375.458  3310.93  3556.28  3360.17  3333.96   
9       1992    42823.3    31086  504.585  3312.78  3541.71  3431.29  3361.36   
10      1993    43464.9  31501.8  545.135     3377  3529.07  3429.24  3436.98   
11      1994    44111.5  31896.1  602.535  3444.28  3593.38  3439.83  3439.04   
12      1995    44840.5  32338.3  636.846  3536.23   3670.9  3507.02  3444.74   
13      1996      45611  32762.3  670.373  3532.26  3770.42  3600.08  3523.76   
14      1997    46126.9    33071   695.12  3503.49  3754.59  3688.97  3596.89   
15      1998    46538.6  33343.7  728.703  3442.87  3727.16  3681.46  3695.64   
16      1999    46857.1  33486.4  751.175   3397.2  3684.12  3655.72  3690.65   
17      2000    47203.5  33686.4  776.064  3381.58  3635.66  3634.41   3675.8   
18      2001    47671.9  33935.9  865.086  3379.15  3614.07  3593.34  3653.31   
19      2002    48183.1  34114.2  914.879  3433.89  3593.84  3564.87  3622.79   
20      2003    48540.2  34200.7  949.649  3503.28  3612.51  3543.78  3611.04   
21      2004    48795.5  34177.6  990.421  3543.55  3663.01  3559.85  3580.46   
22      2005    49113.3    34204  1036.47  3619.42  3690.85  3606.41  3586.11   
23      2006    49315.8  34234.8  1084.39     3631  3751.14   3640.7  3627.49   
24      2007    49290.6  34204.1  1081.11  3609.41  3750.07     3704  3658.86   
25      2008    49265.6  34285.6  1179.51  3639.75  3708.49  3698.72  3707.77   
26      2009      49361  34409.3  1222.86  3677.97  3728.77   3664.7  3707.04   
27      2010    49484.2  34624.5  1278.68  3682.09  3753.95  3700.67  3685.83   
28      2011    49521.7  34772.8  1290.98  3746.41  3772.64  3713.22  3703.31   
29      2012    49771.1  35017.9  1306.99  3830.98   3823.6  3729.47  3719.14   
30      2013    50044.5  35250.8  1328.43  3833.53  3884.82  3791.12  3737.69   
31      2014    50312.6  35369.7  1369.36  3772.41  3863.49   3857.2  3806.16   
32  2015\2\       50438    35388  1401.64   3713.1  3768.14  3842.45  3868.95   
33  2016\3\     50615.2  35477.3  1425.65  3699.16  3693.85  3760.77  3874.02   
34  2017\2\     50685.6  35496.1  1471.22  3684.24  3667.17  3684.09  3787.97   
35       NaN  Projected      NaN      NaN      NaN      NaN      NaN      NaN   
36      2018    50649.8  35443.4   1474.1  3691.45  3638.74  3657.59  3709.45   
37      2019      50634  35401.8   1482.9  3713.51  3645.21  3629.24  3682.76   
38      2020    50654.2  35293.1  1488.69     3728  3664.72  3635.69  3654.22   
39      2021    50643.1  35094.1  1484.05  3716.37  3678.93  3655.15  3660.71   
40      2022    50721.2  35018.6  1516.76  3798.29  3667.41  3669.32  3680.31   
41      2023    50768.2    35022  1524.88  3818.62  3748.53  3657.83  3694.57   
42      2024    50757.7  35122.7  1532.46   3837.6  3768.56  3738.74     3683   
43      2025    50704.1  35266.5   1539.1  3854.23  3787.27  3758.72  3764.47   
44      2026    50671.5  35451.8  1544.59  3867.98  3803.72  3777.38  3784.59   
45      2027    50734.3    35641  1549.05  3879.14  3817.33  3793.79  3803.38   
46      2028      50885  35818.1  1552.48  3887.74  3828.39  3807.36  3819.89   
47      2029    51068.1  35986.9  1555.05  3894.17  3836.93  3818.39  3833.56   

         8        9        10       11       12       13       14       15  \
5   3107.13  3129.86   3037.6  3085.18  3086.22  924.229  13230.9  3376.92   
6   2771.01   2776.4  2788.82  2938.31  2981.88   511.04  12387.7  3438.95   
7   3248.07  3197.34  3110.17   3066.9  2979.12  541.057  11340.8  3168.63   
8   3314.93  3268.43  3239.37  3181.02  3020.07  541.894  11544.4  3313.24   
9   3341.74  3325.43  3302.67  3299.06  3129.01  536.41

In [6]:
df[0].values

array([1980, 1985, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, '2015\\2\\ ', '2016\\3\\ ',
       '2017\\2\\ ', nan, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
       2026, 2027, 2028, 2029], dtype=object)

In [7]:
df[0].isna()

5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35     True
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
Name: 0, dtype: bool

In [8]:
df.loc[df[0].isna(), 0]

35    NaN
Name: 0, dtype: object

NaN values appear in the first column when: 
- there is a subtable lable in the next column
- there is a completely blank row

If empty rows are removed then a blank value must indicate there is a subtable

If row value is bold...
- and indented 3 or 5 times it is a total row
- if not indented it is a row level label

In either case, set it to the current row level

If row value exists and the row is missing then this is a row level label

Table 217.10 gets to 3 row levels

Main instructional building, Percent of schools..., Less then 5...

First level is bold, second has no data, third is indented

Table 217.15 gets to 3 row levels as well...

With a bold row and 2 levels of indentation

This table also has row level labels than span 2 cells! These are 2 bold cells next to each other. Do they count as a total row?

Table 236.30 shows a total row that extends to a double bar, then a new row level label is started

Examples with Total Rows:
- 204.10: Bold, indented 3 spaces, extends to bottom of table
- 204.27: Bold, indented 3 spaces
 - not sure this should indent following row levels
 - this could be difficult to distinguish
- 215.10: Bold, indented 3 spaces, extends to bottom

### Next Steps

- Remove empty rows
- Remove footnotes
- Attched index

In [9]:
rows = pd.MultiIndex.from_arrays([df[0].values])
rows

MultiIndex([(      1980,),
            (      1985,),
            (      1990,),
            (      1991,),
            (      1992,),
            (      1993,),
            (      1994,),
            (      1995,),
            (      1996,),
            (      1997,),
            (      1998,),
            (      1999,),
            (      2000,),
            (      2001,),
            (      2002,),
            (      2003,),
            (      2004,),
            (      2005,),
            (      2006,),
            (      2007,),
            (      2008,),
            (      2009,),
            (      2010,),
            (      2011,),
            (      2012,),
            (      2013,),
            (      2014,),
            ('2015\2\ ',),
            ('2016\3\ ',),
            ('2017\2\ ',),
            (       nan,),
            (      2018,),
            (      2019,),
            (      2020,),
            (      2021,),
            (      2022,),
            (      2023,),
 

In [15]:
row_levels = []
sub_title = []

for val in df[0].values:
    if pd.isnull(val):
        sub_title.append()
        
    sub_title.append("")
    print(val)
    
print(sub_title)

1980
1985
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015\2\ 
2016\3\ 
2017\2\ 
NULL!
nan
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']


In [53]:
rows = tab.end_row - tab.header_lines
row_levels = pd.DataFrame(np.zeros([rows, tab.ROW_LEVELS]),
                         index=range(tab.header_lines+1, tab.end_row+1))

In [54]:
row_levels["subtitle"] = ""

In [57]:
subtitle = ""
row_level = 0

for row in range(tab.header_lines + 1, tab.end_row + 1):
    cell = tab.sheet.cell(row, 0)
    cell_xf = tab.book.xf_list[cell.xf_index]
    is_bold = bool(tab.font[cell_xf.font_index].bold)
    is_empty = bool(cell.value == "")
    
    if is_empty:
        subtitle = tab.sheet.cell(row, 1).value
    
    row_levels.loc[row, "subtitle"] = subtitle
    row_levels.loc[row, row_level] = cell.value

In [58]:
row_levels

0    1    2    3    4    5    6   subtitle
5       1980  0.0  0.0  0.0  0.0  0.0  0.0           
6       1985  0.0  0.0  0.0  0.0  0.0  0.0           
7       1990  0.0  0.0  0.0  0.0  0.0  0.0           
8       1991  0.0  0.0  0.0  0.0  0.0  0.0           
9       1992  0.0  0.0  0.0  0.0  0.0  0.0           
10      1993  0.0  0.0  0.0  0.0  0.0  0.0           
11      1994  0.0  0.0  0.0  0.0  0.0  0.0           
12      1995  0.0  0.0  0.0  0.0  0.0  0.0           
13      1996  0.0  0.0  0.0  0.0  0.0  0.0           
14      1997  0.0  0.0  0.0  0.0  0.0  0.0           
15      1998  0.0  0.0  0.0  0.0  0.0  0.0           
16      1999  0.0  0.0  0.0  0.0  0.0  0.0           
17      2000  0.0  0.0  0.0  0.0  0.0  0.0           
18      2001  0.0  0.0  0.0  0.0  0.0  0.0           
19      2002  0.0  0.0  0.0  0.0  0.0  0.0           
20      2003  0.0  0.0  0.0  0.0  0.0  0.0           
21      2004  0.0  0.0  0.0  0.0  0.0  0.0           
22      2005  0.0  0.0  0.0  0.0  0.0  0.0           
23      2006  0.0  0.0  0.0  0.0  0.0  0.0           
24      2007  0.0  0.0  0.0  0.0  0.0  0.0           
25      2008  0.0  0.0  0.0  0.0  0.0  0.0           
26      2009  0.0  0.0  0.0  0.0  0.0  0.0           
27      2010  0.0  0.0  0.0  0.0  0.0  0.0           
28      2011  0.0  0.0  0.0  0.0  0.0  0.0           
29      2012  0.0  0.0  0.0  0.0  0.0  0.0           
30      2013  0.0  0.0  0.0  0.0  0.0  0.0           
31      2014  0.0  0.0  0.0  0.0  0.0  0.0           
32  2015\2\   0.0  0.0  0.0  0.0  0.0  0.0           
33  2016\3\   0.0  0.0  0.0  0.0  0.0  0.0           
34  2017\2\   0.0  0.0  0.0  0.0  0.0  0.0           
35            0.0  0.0  0.0  0.0  0.0  0.0  Projected
36      2018  0.0  0.0  0.0  0.0  0.0  0.0  Projected
37      2019  0.0  0.0  0.0  0.0  0.0  0.0  Projected
38      2020  0.0  0.0  0.0  0.0  0.0  0.0  Projected
39      2021  0.0  0.0  0.0  0.0  0.0  0.0  Projected
40      2022  0.0  0.0  0.0  0.0  0.0  0.0  Projected
41      2023  0.0  0.0  0.0  0.0  0.0  0.0  Projected
42      2024  0.0  0.0  0.0  0.0  0.0  0.0  Projected
43      2025  0.0  0.0  0.0  0.0  0.0  0.0  Projected
44      2026  0.0  0.0  0.0  0.0  0.0  0.0  Projected
45      2027  0.0  0.0  0.0  0.0  0.0  0.0  Projected
46      2028  0.0  0.0  0.0  0.0  0.0  0.0  Projected
47      2029  0.0  0.0  0.0  0.0  0.0  0.0  Projected

In [134]:
def get_leading_spaces(string):
    string = str(string)
    res = re.search(r"[^ ]", string)
    
    if res:
        return res.start()
    else:
        return 0
        

In [192]:
def row_info(table):
    subtitle = ""
    row_level = 0
    indent_level = 0
    rows = table.end_row - table.header_lines
    
    empty = np.empty([rows, table.ROW_LEVELS])
    empty[:] = np.NaN
    
    row_levels = pd.DataFrame(empty,
                              index=range(table.header_lines+1, table.end_row+1))

    for row in range(table.header_lines + 1, table.end_row + 1):
        cell = table.sheet.cell(row, 0)
        cell_xf = table.book.xf_list[cell.xf_index]
        is_bold = bool(table.font[cell_xf.font_index].bold)
        is_empty = bool(cell.value == "")
        indents = get_leading_spaces(cell.value)
        is_total = is_bold and (indents == 3 or indents == 5)

        
        if is_empty and table.sheet.cell(row,1).value != "":
            subtitle = table.sheet.cell(row, 1).value
        
        
        if indents in [0,3,5]:
            indent_level = 0
        else:
            indent_level = indents / 2
        
        
        if is_total:
            row_level = 0
            row_levels.loc[row, "subtitle"] = subtitle
            row_levels.loc[row, row_level] = cell.value
            row_level = 1
        elif is_bold:
            row_level = 0
            row_levels.loc[row, "subtitle"] = subtitle
            row_levels.loc[row, row_level] = cell.value
            row_level = 1
        else: 
            row_levels.loc[row, "subtitle"] = subtitle
            row_levels.loc[row, row_level+indent_level] = cell.value
        
    # forward fill row levels
    row_levels = row_levels.ffill(axis=1).ffill(axis=0)
    is_duplicate = row_levels.apply(lambda row: row.duplicated(), axis=1)
    row_levels = row_levels.where(~is_duplicate, "")
    
    return row_levels

In [193]:
row_info(tables['203.10'])

0 1 2 3 4 5 6   subtitle
5       1980                       
6       1985                       
7       1990                       
8       1991                       
9       1992                       
10      1993                       
11      1994                       
12      1995                       
13      1996                       
14      1997                       
15      1998                       
16      1999                       
17      2000                       
18      2001                       
19      2002                       
20      2003                       
21      2004                       
22      2005                       
23      2006                       
24      2007                       
25      2008                       
26      2009                       
27      2010                       
28      2011                       
29      2012                       
30      2013                       
31      2014                       
32  2015\2\                        
33  2016\3\                        
34  2017\2\                        
35                        Projected
36      2018              Projected
37      2019              Projected
38      2020              Projected
39      2021              Projected
40      2022              Projected
41      2023              Projected
42      2024              Projected
43      2025              Projected
44      2026              Projected
45      2027              Projected
46      2028              Projected
47      2029              Projected

In [194]:
row_info(tables['203.50'])

0         1 2 3 4 5 6 subtitle
4   United States                             
5   United States      1995                   
6   United States      2000                   
7   United States      2001                   
8   United States      2002                   
9   United States      2003                   
10  United States      2004                   
11  United States      2005                   
12  United States      2006                   
13  United States      2007                   
14  United States      2008                   
15  United States      2009                   
16  United States      2010                   
17  United States      2011                   
18  United States      2012                   
19  United States      2013                   
20  United States      2014                   
21  United States  2015\3\                    
22  United States  2016\4\                    
23  United States  2017\3\                    
24  United States  2018\5\                    
25  United States  2019\5\                    
26  United States  2020\5\                    
27  United States  2021\5\                    
28  United States  2022\5\                    
29  United States  2023\5\                    
30  United States  2024\5\                    
31  United States  2025\5\                    
32  United States  2026\5\                    
33  United States  2027\5\                    
34  United States  2028\5\                    
35  United States  2029\5\                    
36      Northeast                             
37      Northeast      1995                   
38      Northeast      2000                   
39      Northeast      2005                   
40      Northeast      2010                   
41      Northeast      2014                   
42      Northeast      2015                   
43      Northeast      2016                   
44      Northeast      2017                   
45        Midwest                             
46        Midwest      1995                   
47        Midwest      2000                   
48        Midwest      2005                   
49        Midwest      2010                   
50        Midwest      2014                   
51        Midwest      2015                   
52        Midwest      2016                   
53        Midwest      2017                   
54          South                             
55          South      1995                   
56          South      2000                   
57          South      2005                   
58          South      2010                   
59          South      2014                   
60          South      2015                   
61          South      2016                   
62          South      2017                   
63           West                             
64           West      1995                   
65           West      2000                   
66           West      2005                   
67           West      2010                   
68           West      2014                   
69           West  2015\3\                    
70           West  2016\4\                    
71           West  2017\3\

In [195]:
row_info(tables['204.10'])

0                      1 2 3 4 5 6 subtitle
4      United States                                           
5      United States                Alabama                    
6      United States                 Alaska                    
7      United States                Arizona                    
8      United States               Arkansas                    
9      United States             California                    
10     United States               Colorado                    
11     United States            Connecticut                    
12     United States               Delaware                    
13     United States   District of Columbia                    
14     United States                Florida                    
15     United States                Georgia                    
16     United States                 Hawaii                    
17     United States                  Idaho                    
18     United States               Illinois                    
19     United States                Indiana                    
20     United States                   Iowa                    
21     United States                 Kansas                    
22     United States               Kentucky                    
23     United States              Louisiana                    
24     United States                  Maine                    
25     United States               Maryland                    
26     United States          Massachusetts                    
27     United States               Michigan                    
28     United States              Minnesota                    
29     United States            Mississippi                    
30     United States               Missouri                    
31     United States                Montana                    
32     United States               Nebraska                    
33     United States                 Nevada                    
34     United States          New Hampshire                    
35     United States             New Jersey                    
36     United States             New Mexico                    
37     United States               New York                    
38     United States         North Carolina                    
39     United States           North Dakota                    
40     United States                   Ohio                    
41     United States               Oklahoma                    
42     United States                 Oregon                    
43     United States           Pennsylvania                    
44     United States           Rhode Island                    
45     United States         South Carolina                    
46     United States           South Dakota                    
47     United States              Tennessee                    
48     United States                  Texas                    
49     United States                   Utah                    
50     United States                Vermont                    
51     United States               Virginia                    
52     United States             Washington                    
53     United States          West Virginia                    
54     United States              Wisconsin                    
55     United States                Wyoming

In [196]:
row_info(tables['204.27'])

0  \
4      Total ........................................   
5      Total ........................................   
6      Total ........................................   
7      Total ........................................   
8      Total ........................................   
9      Total ........................................   
10     Total ........................................   
11     Total ........................................   
12     Total ........................................   
13     Total ........................................   
14     Total ........................................   
15     Total ........................................   
16     Total ........................................   
17     Total ........................................   
18     Total ........................................   
19     Total ........................................   
20     Total ........................................   
21     Total ........................................   
22     Total ........................................   
23     Total ........................................   
24     Total ........................................   
25     Total ........................................   
26     Total ........................................   
27     Total ........................................   
28     Total ........................................   
29     Total ........................................   
30     Total ........................................   
31     Total ........................................   
32     Total ........................................   
33     Total ........................................   
34     Total ........................................   
35     Total ........................................   
36     Total ........................................   
37     Total ........................................   
38     Total ........................................   
39     Total ........................................   
40     Total ........................................   
41     Total ........................................   
42     Total ........................................   
43     Total ........................................   
44     Total ........................................   
45     Total ........................................   
46     Total ........................................   
47     Total ........................................   
48     Total ........................................   
49     Total ........................................   
50     Total ........................................   
51     Total ........................................   
52     Total ........................................   
53     Total ........................................   
54     Total ........................................   
55     Total ........................................   
56     Total ........................................   
57     Total ........................................   
58     Total ........................................   
59     Total ........................................   
60     Total ........................................   
61     Total ........................................   
62     Total ........................................   

                                                    1  \
4                                                       
5   30 most commonly reported\n   home languages o...   
6   30 most commonly reported\n   home languages o...   
7   30 most commonly reported\n   home languages o...   
8   30 most commonly reported\n   home languages o...   
9   30 most commonly reported\n   home languages o...   
10  30 most commonly reported\n   home languages o...   
11  30 most commonly reported\n   home languages o...   
12  30 most commonly reported\n   home languages o...   
13  30 most commonly reported\n   home languages o...   
14  

In [197]:
row_info(tables['213.10'])

0 1 2 3 4 5 6                 subtitle
8                                                        Number
9          1949-50\2\ ....                               Number
10         1959-60\2\ ....                               Number
11         1969-70\2\ ....                               Number
12  Fall 1980\2\ .........                               Number
13          Fall 1990 ....                               Number
14                                                       Number
15          Fall 2000 ....                               Number
16       Fall 2002 .......                               Number
17       Fall 2003 .......                               Number
18       Fall 2004 .......                               Number
19       Fall 2005 .......                               Number
20                                                       Number
21       Fall 2006 .......                               Number
22       Fall 2007 .......                               Number
23       Fall 2008 .......                               Number
24       Fall 2009 .......                               Number
25       Fall 2010 .......                               Number
26                                                       Number
27       Fall 2011 .......                               Number
28       Fall 2012 .......                               Number
29       Fall 2013 .......                               Number
30       Fall 2014 .......                               Number
31       Fall 2015 .......                               Number
32                                                       Number
33       Fall 2016 .......                               Number
34       Fall 2017 .......                               Number
35                                      Percentage distribution
36         1949-50\2\ ....              Percentage distribution
37         1959-60\2\ ....              Percentage distribution
38         1969-70\2\ ....              Percentage distribution
39  Fall 1980\2\ .........              Percentage distribution
40          Fall 1990 ....              Percentage distribution
41                                      Percentage distribution
42          Fall 2000 ....              Percentage distribution
43       Fall 2002 .......              Percentage distribution
44       Fall 2003 .......              Percentage distribution
45       Fall 2004 .......              Percentage distribution
46       Fall 2005 .......              Percentage distribution
47                                      Percentage distribution
48       Fall 2006 .......              Percentage distribution
49       Fall 2007 .......              Percentage distribution
50       Fall 2008 .......              Percentage distribution
51       Fall 2009 .......              Percentage distribution
52       Fall 2010 .......              Percentage distribution
53                                      Percentage distribution
54       Fall 2011 .......              Percentage distribution
55       Fall 2012 .......              Percentage distribution
56       Fall 2013 .......              Percentage distribution
57       Fall 2014 .......              Percentage distribution
58       Fall 2015 .......              Percentage distribution
59                                      Percentage distribution
60       Fall 2016 .......              Percentage distribution
61       Fall 2017 .......              Percentage distribution
62                                      Pupils per staff member
63         1949-50\2\ ....              Pupils per staff member
64         1959-60\2\ ....              Pupils per staff member
65         1969-70\2\ ....              Pupils per staff member
66  Fall 1980\2\ .........              Pupils per staff member
67          Fall 1990 ....              Pupils per staff member
68                                      Pupils per staff member
69          Fall 2000 ....              Pupils per staff 

In [198]:
row_info(tables['215.10'])

0  \
4       Districts with more than\n      15,000 stud...   
5       Districts with more than\n      15,000 stud...   
6       Districts with more than\n      15,000 stud...   
7       Districts with more than\n      15,000 stud...   
8       Districts with more than\n      15,000 stud...   
9       Districts with more than\n      15,000 stud...   
10      Districts with more than\n      15,000 stud...   
11      Districts with more than\n      15,000 stud...   
12      Districts with more than\n      15,000 stud...   
13      Districts with more than\n      15,000 stud...   
14      Districts with more than\n      15,000 stud...   
15      Districts with more than\n      15,000 stud...   
16      Districts with more than\n      15,000 stud...   
17      Districts with more than\n      15,000 stud...   
18      Districts with more than\n      15,000 stud...   
19      Districts with more than\n      15,000 stud...   
20      Districts with more than\n      15,000 stud...   
21      Districts with more than\n      15,000 stud...   
22      Districts with more than\n      15,000 stud...   
23      Districts with more than\n      15,000 stud...   
24      Districts with more than\n      15,000 stud...   
25      Districts with more than\n      15,000 stud...   
26      Districts with more than\n      15,000 stud...   
27      Districts with more than\n      15,000 stud...   
28      Districts with more than\n      15,000 stud...   
29      Districts with more than\n      15,000 stud...   
30      Districts with more than\n      15,000 stud...   
31      Districts with more than\n      15,000 stud...   
32      Districts with more than\n      15,000 stud...   
33      Districts with more than\n      15,000 stud...   
34      Districts with more than\n      15,000 stud...   
35      Districts with more than\n      15,000 stud...   
36      Districts with more than\n      15,000 stud...   
37      Districts with more than\n      15,000 stud...   
38      Districts with more than\n      15,000 stud...   
39      Districts with more than\n      15,000 stud...   
40      Districts with more than\n      15,000 stud...   
41      Districts with more than\n      15,000 stud...   
42      Districts with more than\n      15,000 stud...   
43      Districts with more than\n      15,000 stud...   
44      Districts with more than\n      15,000 stud...   
45      Districts with more than\n      15,000 stud...   
46      Districts with more than\n      15,000 stud...   
47      Districts with more than\n      15,000 stud...   
48      Districts with more than\n      15,000 stud...   
49      Districts with more than\n      15,000 stud...   
50      Districts with more than\n      15,000 stud...   
51      Districts with more than\n      15,000 stud...   
52      Districts with more than\n      15,000 stud...   
53      Districts with more than\n      15,000 stud...   
54      Districts with more than\n      15,000 stud...   
55      Districts with more than\n      15,000 stud...   
56      Districts with more than\n      15,000 stud...   
57      Districts with more than\n      15,000 stud...   
58      Districts with more than\n      15,000 stud...   
59      Districts with more than\n      15,000 stud...   
60      Districts with more than\n      15,000 stud...   
61      Districts with more than\n      15,000 stud...   
62      Districts with more than\n      15,000 stud...   
63      Districts with more than\n      15,000 stud...   
64      Districts with more than\n      15,000 stud...   
65      Districts with more than\n      15,000 stud...   
66      Districts with more than\n      15,000 stud...   
67      Districts with more than\n      15,000 stud...   
68      Districts with more than\n      15,000 stud...   
69      Districts with more than\n      15,000 stud...   
70      Districts with more than\n      15,000 stud...   
71      Districts with more than\n      15,000 stud...   
72      Districts with more than\n      15,000 stud

In [199]:
row_info(tables['217.10'])

0  \
5   Estimated number of schools .....................   
6                                                       
7                         Main instructional building   
8                         Main instructional building   
9                         Main instructional building   
10                        Main instructional building   
11                        Main instructional building   
12                        Main instructional building   
13                        Main instructional building   
14                        Main instructional building   
15                        Main instructional building   
16                        Main instructional building   
17      Permanent buildings \n   (percent of schools)   
18      Permanent buildings \n   (percent of schools)   
19      Permanent buildings \n   (percent of schools)   
20      Permanent buildings \n   (percent of schools)   
21      Permanent buildings \n   (percent of schools)   
22      Permanent buildings \n   (percent of schools)   
23      Permanent buildings \n   (percent of schools)   
24      Permanent buildings \n   (percent of schools)   
25      Permanent buildings \n   (percent of schools)   
26      Permanent buildings \n   (percent of schools)   
27      Permanent buildings \n   (percent of schools)   
28      Permanent buildings \n   (percent of schools)   
29      Permanent buildings \n   (percent of schools)   
30      Permanent buildings \n   (percent of schools)   
31      Permanent buildings \n   (percent of schools)   
32      Permanent buildings \n   (percent of schools)   
33      Permanent buildings \n   (percent of schools)   
34      Permanent buildings \n   (percent of schools)   
35  Portable (temporary) buildings\n   (percent of...   
36  Portable (temporary) buildings\n   (percent of...   
37  Portable (temporary) buildings\n   (percent of...   
38  Portable (temporary) buildings\n   (percent of...   
39  Portable (temporary) buildings\n   (percent of...   
40  Portable (temporary) buildings\n   (percent of...   
41  Portable (temporary) buildings\n   (percent of...   
42  Portable (temporary) buildings\n   (percent of...   
43  Portable (temporary) buildings\n   (percent of...   
44  Portable (temporary) buildings\n   (percent of...   
45  Portable (temporary) buildings\n   (percent of...   
46  Portable (temporary) buildings\n   (percent of...   
47  Portable (temporary) buildings\n   (percent of...   
48  Portable (temporary) buildings\n   (percent of...   
49  Portable (temporary) buildings\n   (percent of...   
50  Portable (temporary) buildings\n   (percent of...   
51  Portable (temporary) buildings\n   (percent of...   

                                                    1  \
5                                                       
6                                                       
7                                                       
8       Percent of schools, by functional \n   age\2\   
9       Percent of schools, by functional \n   age\2\   
10      Percent of schools, by functional \n   age\2\   
11      Percent of schools, by functional \n   age\2\   
12      Percent of schools, by functional \n   age\2\   
13                                      Average years   
14                                      Average years   
15                                      Average years   
16                                                      
17                                                      
18  School has permanent buildings ..................   
19  School has permanent buildings ..................   
20  School has permanent buildings ..................   
21  School has permanent buildings ..................   
22  School has permanent buildings ..................   
23  School has permanent buildings ..................   
24                                                      
25                                                      
26                                                      
27  

Multiline row header in this table.

In [200]:
row_info(tables['217.15'])

0 1  \
5    Roofs--percent of schools with plans ............     
6    Roofs--percent of schools with plans ............     
7    Roofs--percent of schools with plans ............     
8    Roofs--percent of schools with plans ............     
9    Roofs--percent of schools with plans ............     
10   Roofs--percent of schools with plans ............     
11   Roofs--percent of schools with plans ............     
12   Framing, floors, foundations--percent of schoo...     
13      plans ........................................     
14      plans ........................................     
15      plans ........................................     
16      plans ........................................     
17      plans ........................................     
18      plans ........................................     
19      plans ........................................     
20   Exterior walls, finishes--percent of schools w...     
21   Exterior walls, finishes--percent of schools w...     
22   Exterior walls, finishes--percent of schools w...     
23   Exterior walls, finishes--percent of schools w...     
24   Exterior walls, finishes--percent of schools w...     
25   Exterior walls, finishes--percent of schools w...     
26   Exterior walls, finishes--percent of schools w...     
27   Windows, doors--percent of schools with plans ...     
28   Windows, doors--percent of schools with plans ...     
29   Windows, doors--percent of schools with plans ...     
30   Windows, doors--percent of schools with plans ...     
31   Windows, doors--percent of schools with plans ...     
32   Windows, doors--percent of schools with plans ...     
33   Windows, doors--percent of schools with plans ...     
34   Interior finishes, trim--percent of schools wi...     
35   Interior finishes, trim--percent of schools wi...     
36   Interior finishes, trim--percent of schools wi...     
37   Interior finishes, trim--percent of schools wi...     
38   Interior finishes, trim--percent of schools wi...     
39   Interior finishes, trim--percent of schools wi...     
40   Interior finishes, trim--percent of schools wi...     
41   Plumbing/lavatories--percent of schools with p...     
42   Plumbing/lavatories--percent of schools with p...     
43   Plumbing/lavatories--percent of schools with p...     
44   Plumbing/lavatories--percent of schools with p...     
45   Plumbing/lavatories--percent of schools with p...     
46   Plumbing/lavatories--percent of schools with p...     
47   Plumbing/lavatories--percent of schools with p...     
48   Heating system--percent of schools with plans ...     
49   Heating system--percent of schools with plans ...     
50   Heating system--percent of schools with plans ...     
51   Heating system--percent of schools with plans ...     
52   Heating system--percent of schools with plans ...     
53   Heating system--percent of schools with plans ...     
54   Heating system--percent of schools with plans ...     
55   Air conditioning system--percent of schools wi...     
56   Air conditioning system--percent of schools wi...     
57   Air conditioning system--percent of schools wi...     
58   Air conditioning system--percent of schools wi...     
59   Air conditioning system--percent of schools wi...     
60   Air conditioning system--percent of schools wi...     
61   Air conditioning system--percent of schools wi...     
62   Ventilation/filtration system--percent of scho...     
63      plans ........................................     
64      plans ........................................     
65      plans ........................................     
66      plans ........................................     
67      plans ........................................     
68      plans ........................................     
69      plans ........................................     
70   Electrical system--percent of schools with pla...     
71   Electrical system--percent o

In [185]:
row_info(tables['219.70'])

0   1   2   3   4   5   6 subtitle
5     1960\2\  NaN NaN NaN NaN NaN NaN         
6     1967\3\  NaN NaN NaN NaN NaN NaN         
7     1968\3\  NaN NaN NaN NaN NaN NaN         
8     1969\3\  NaN NaN NaN NaN NaN NaN         
9     1970\3\  NaN NaN NaN NaN NaN NaN         
10    1971\3\  NaN NaN NaN NaN NaN NaN         
11        1972 NaN NaN NaN NaN NaN NaN         
12        1973 NaN NaN NaN NaN NaN NaN         
13        1974 NaN NaN NaN NaN NaN NaN         
14        1975 NaN NaN NaN NaN NaN NaN         
15        1976 NaN NaN NaN NaN NaN NaN         
16        1977 NaN NaN NaN NaN NaN NaN         
17        1978 NaN NaN NaN NaN NaN NaN         
18        1979 NaN NaN NaN NaN NaN NaN         
19        1980 NaN NaN NaN NaN NaN NaN         
20        1981 NaN NaN NaN NaN NaN NaN         
21        1982 NaN NaN NaN NaN NaN NaN         
22        1983 NaN NaN NaN NaN NaN NaN         
23        1984 NaN NaN NaN NaN NaN NaN         
24        1985 NaN NaN NaN NaN NaN NaN         
25        1986 NaN NaN NaN NaN NaN NaN         
26        1987 NaN NaN NaN NaN NaN NaN         
27        1988 NaN NaN NaN NaN NaN NaN         
28        1989 NaN NaN NaN NaN NaN NaN         
29        1990 NaN NaN NaN NaN NaN NaN         
30        1991 NaN NaN NaN NaN NaN NaN         
31    1992\4\  NaN NaN NaN NaN NaN NaN         
32    1993\4\  NaN NaN NaN NaN NaN NaN         
33    1994\4\  NaN NaN NaN NaN NaN NaN         
34    1995\4\  NaN NaN NaN NaN NaN NaN         
35    1996\4\  NaN NaN NaN NaN NaN NaN         
36    1997\4\  NaN NaN NaN NaN NaN NaN         
37    1998\4\  NaN NaN NaN NaN NaN NaN         
38    1999\4\  NaN NaN NaN NaN NaN NaN         
39    2000\4\  NaN NaN NaN NaN NaN NaN         
40    2001\4\  NaN NaN NaN NaN NaN NaN         
41    2002\4\  NaN NaN NaN NaN NaN NaN         
42  2003\4,5\  NaN NaN NaN NaN NaN NaN         
43  2004\4,5\  NaN NaN NaN NaN NaN NaN         
44  2005\4,5\  NaN NaN NaN NaN NaN NaN         
45  2006\4,5\  NaN NaN NaN NaN NaN NaN         
46  2007\4,5\  NaN NaN NaN NaN NaN NaN         
47  2008\4,5\  NaN NaN NaN NaN NaN NaN         
48  2009\4,5\  NaN NaN NaN NaN NaN NaN         
49  2010\4,5\  NaN NaN NaN NaN NaN NaN         
50  2011\4,5\  NaN NaN NaN NaN NaN NaN         
51  2012\4,5\  NaN NaN NaN NaN NaN NaN         
52  2013\4,5\  NaN NaN NaN NaN NaN NaN         
53  2014\4,5\  NaN NaN NaN NaN NaN NaN         
54  2015\4,5\  NaN NaN NaN NaN NaN NaN         
55  2016\4,5\  NaN NaN NaN NaN NaN NaN         
56  2017\4,5\  NaN NaN NaN NaN NaN NaN         
57  2018\4,5\  NaN NaN NaN NaN NaN NaN

Does not handle "Other Juristictions" the way they wanted

In [201]:
row_info(tables['236.30'])

0                                 1  \
7      United States ........                                     
8      United States ........      Alabama ....................   
9      United States ........         Alaska ..................   
10     United States ........     Arizona .....................   
11     United States ........       Arkansas ..................   
12     United States ........      California .................   
13     United States ........                                     
14     United States ........     Colorado ....................   
15     United States ........       Connecticut ...............   
16     United States ........       Delaware ..................   
17     United States ........     District of Columbia ........   
18     United States ........        Florida ..................   
19     United States ........                                     
20     United States ........         Georgia .................   
21     United States ........      Hawaii .....................   
22     United States ........    Idaho ........................   
23     United States ........        Illinois .................   
24     United States ........      Indiana ....................   
25     United States ........                                     
26     United States ........     Iowa ........................   
27     United States ........      Kansas .....................   
28     United States ........        Kentucky .................   
29     United States ........     Louisiana ...................   
30     United States ........       Maine .....................   
31     United States ........                                     
32     United States ........     Maryland ....................   
33     United States ........      Massachusetts ..............   
34     United States ........    Michigan .....................   
35     United States ........     Minnesota ...................   
36     United States ........         Mississippi .............   
37     United States ........                                     
38     United States ........        Missouri .................   
39     United States ........     Montana .....................   
40     United States ........     Nebraska ....................   
41     United States ........       Nevada ....................   
42     United States ........  New Hampshire ..................   
43     United States ........                                     
44     United States ........      New Jersey .................   
45     United States ........      New Mexico .................   
46     United States ........       New York ..................   
47     United States ........        North Carolina ...........   
48     United States ........     North Dakota ................   
49     United States ........                                     
50     United States ........      Ohio .......................   
51     United States ........     Oklahoma ....................   
52     United States ........     Oregon ......................   
53     United States ........      Pennsylvania ...............   
54     United States ........       Rhode Island ..............   
55     United States ........                                     
56     United States ........      South Carolina .............   
57     United States ........        South Dakota .............   
58     United States ........         Tennessee ...............   
59     United States ........        Texas ....................   
60     United States ........         Utah ....................   
61     United States ........                                     
62     United States ........      Vermont ....................   
63     United States ........     Virginia ....................   
64     United States ........     Washington ..................   
65     United States ........         West Virginia ...........   
66     U

In [202]:
row_info(tables['318.45'])

0                     1 2 3 4 5 6  \
5                                              
6      Total                                   
7      Total  2008-09 ............             
8      Total  2009-10 ............             
9      Total  2010-11 ............             
10     Total  2011-12 ............             
11     Total  2012-13 ............             
12     Total                                   
13     Total  2013-14 ............             
14     Total  2014-15 ............             
15     Total  2015-16 ............             
16     Total  2016-17 ............             
17     Total  2017-18 ............             
18     Total                                   
19     Males                                   
20     Males  2008-09 ............             
21     Males  2009-10 ............             
22     Males  2010-11 ............             
23     Males  2011-12 ............             
24     Males  2012-13 ............             
25     Males                                   
26     Males  2013-14 ............             
27     Males  2014-15 ............             
28     Males  2015-16 ............             
29     Males  2016-17 ............             
30     Males  2017-18 ............             
31     Males                                   
32   Females                                   
33   Females  2008-09 ............             
34   Females  2009-10 ............             
35   Females  2010-11 ............             
36   Females  2011-12 ............             
37   Females  2012-13 ............             
38   Females                                   
39   Females  2013-14 ............             
40   Females  2014-15 ............             
41   Females  2015-16 ............             
42   Females  2016-17 ............             
43   Females  2017-18 ............             
44   Females                                   
45     Total                                   
46     Total  2008-09 ............             
47     Total  2009-10 ............             
48     Total  2010-11 ............             
49     Total  2011-12 ............             
50     Total  2012-13 ............             
51     Total                                   
52     Total  2013-14 ............             
53     Total  2014-15 ............             
54     Total  2015-16 ............             
55     Total  2016-17 ............             
56     Total  2017-18 ............             
57     Total                                   
58     Males                                   
59     Males  2008-09 ............             
60     Males  2009-10 ............             
61     Males  2010-11 ............             
62     Males  2011-12 ............             
63     Males  2012-13 ............             
64     Males                                   
65     Males  2013-14 ............             
66     Males  2014-15 ............             
67     Males  2015-16 ............             
68     Males  2016-17 ............             
69     Males  2017-18 ............             
70     Males                                   
71   Females                                   
72   Females  2008-09 ............             
73   Females  2009-10 ............             
74   Females  2010-11 ............             
75   Females  2011-12 ............             
76   Females  2012-13 ............             
77   Females                                   
78   Females  2013-14 ............             
79   Females  2014-15 ............             
80   Females  2015-16 ............             
81   Females  2016-17 ............             
82   Females  2017-18 ............             
83   Females                                   
84     Total                                   
85     Total  2008-09 ............             
86     Total  2009-10 ............             
87     Total  2010-11 .....